#!/usr/bin/env bash

set -eu

usage () {
	exec 1>&2
	echo "Usage: ${0##*/} [-w] PPID [PPID..]"
	echo
	echo "-w	Include LWP (lightweight processes / threads) in listing."
	echo
	echo "Lists a parent pid and all of its childs one per line."
	exit 2
}

get_childs_tid () {
	local searchpid="$1"
	local pid
	local tid

	ps -Leo pid:1=,tid:1= q ${searchpid} | \
		egrep "^${searchpid}" | \
		while read pid tid
		do
			echo $tid
		done
}

get_childs_ps () {
	local searchpid="$1"
	local ppid
	local pid
	local tid
	declare -A searchdone

	ps -Leo ppid:1=,pid:1=,tid:1= | \
		egrep "^${searchpid}" | \
		while read ppid pid tid
		do
			if [ -z ${searchdone[$pid]-} ]; then
				get_childs_ps $pid
				get_childs_tid $pid
				searchdone[$pid]=1
			fi
		done

}

main () {
	local list_lwp=0

	while getopts "w" o; do
		case "${o-}" in
			w) list_lwp=1;;
			*) usage;;
		esac
	done
	shift $((OPTIND-1))

	[ -z ${1-} ] && usage

	while [ ! -z ${1-} ]
	do
		get_childs_ps $1
		if [ $list_lwp -eq 1 ]; then
			get_childs_tid $1
		else
			echo $1
		fi
		shift
	done | sort | uniq
}

main "$@"
